apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: {{ include "spark.namespace" . }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - services
      - configmaps
      - events
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: {{ include "spark.namespace" . }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ include "spark.namespace" . }}
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
