apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-thrift-defaults
  namespace: spark
data:
  spark-defaults.conf: |
    spark.master                                                k8s://https://kubernetes.default.svc
    spark.submit.deployMode                                     client
    spark.kubernetes.driver.node.selector.spark-driver          support
    spark.kubernetes.executor.node.selector.spark-executor      support
    spark.kubernetes.authenticate.driver.serviceAccountName     spark
    spark.kubernetes.authenticate.executor.serviceAccountName   spark
    spark.kubernetes.container.image                            wgqacr.azurecr.io/wgq/spark:3.5.7-20260317
    spark.kubernetes.namespace                                  spark
    spark.driver.cores                                          1
    spark.driver.memory                                         3g
    spark.executor.cores                                        1
    spark.executor.memory                                       4g
    spark.dynamicAllocation.enabled                             true
    spark.dynamicAllocation.shuffleTracking.enabled             true
    spark.dynamicAllocation.minExecutors                        0
    spark.dynamicAllocation.maxExecutors                        20
    spark.dynamicAllocation.executorIdleTimeout                 600s
    spark.sql.catalogImplementation                             hive
    spark.hadoop.hive.metastore.uris                            thrift://hive-metastore.hive.svc:9083
    spark.sql.warehouse.dir                                     abfs://spark@wgqsahn.dfs.core.windows.net/hive/warehouse
    spark.sql.shuffle.partitions                                200
    spark.sql.adaptive.enabled                                  true
    spark.eventLog.enabled                                      true
    spark.eventLog.dir                                          abfs://history@wgqsahn.dfs.core.windows.net/spark/eventlogs
    spark.eventLog.rolling.enabled                              true
    spark.eventLog.rolling.maxFileSize                           128m
    spark.driver.extraJavaOptions                               -XX:+UseG1GC -XX:MaxGCPauseMillis=200 
    spark.executor.extraJavaOptions                             -XX:+UseG1GC -XX:MaxGCPauseMillis=200 
    spark.network.timeout                                       800s
    spark.executor.heartbeatInterval                            60s
    spark.hadoop.fs.azure.account.auth.type                     Custom
    spark.hadoop.fs.azure.account.oauth.provider.type           com.github.azure.hadoop.custom.auth.MSIFileCachedAccessTokenProvider
    spark.hadoop.fs.azure.account.hns.enabled                   true
    spark.hadoop.fs.azure.account.oauth2.client.id              f5e0c725-5ace-4369-9ad4-6dceedbf6d79
    spark.hadoop.fs.azure.account.oauth2.msi.endpoint           http://169.254.169.254/metadata/identity/oauth2/token
    spark.hadoop.fs.azure.account.oauth2.msi.tenant             16b3c013-d300-468d-ac64-7eda0820b6d3
    spark.hadoop.fs.azure.enable.check.access                   false
    spark.security.authentication                               false
    spark.hadoop.fs.azure.custom.token.file.cache.path          /tmp/.azure
    spark.hiveconf.hive.server2.thrift.port                     10000
    spark.hiveconf.hive.server2.thrift.bind.host                0.0.0.0
    spark.driver.host                                           spark-thrift-server.spark.svc
    spark.driver.port                                           7078
    spark.driver.blockManager.port                              7079
    spark.driver.bindAddress                                    0.0.0.0
    spark.ui.port                                               4040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-thrift-server
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-thrift-server
  template:
    metadata:
      labels:
        app: spark-thrift-server
    spec:
      securityContext:
        runAsUser: 185
        runAsGroup: 0
        fsGroup: 0
      nodeSelector:
        spark-thrift-server: "support"
      serviceAccountName: spark
      containers:
        - name: spark-thrift-server
          image: wgqacr.azurecr.io/wgq/spark:3.5.7-20260317
          command: ["/opt/spark/sbin/start-thriftserver.sh"]
          env:
            - name: SPARK_USER
              value: spark
            - name:  "TZ"
              value: "Asia/Shanghai"
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SPARK_DRIVER_BIND_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: spark-thrift
              containerPort: 10000
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: "/opt/spark/conf"
              name: spark-thrift-server-volume
      volumes:
        - name: spark-thrift-server-volume
          configMap:
            name: spark-thrift-defaults
---
apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-server
  namespace: spark
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: spark-thrift-server
  ports:
    - name: thrift-server
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: driver-ui
      protocol: TCP
      port: 4040
      targetPort: 4040



---
apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-driver
  namespace: spark
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: spark-thrift-driver
  ports:
    - name: block-manager
      protocol: TCP
      port: 7078
      targetPort: 7078
    - name: driver-rpc
      protocol: TCP
      port: 7079
      targetPort: 7079
