apiVersion: v1
kind: Pod
spec:
  terminationGracePeriodSeconds: 3600
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: spark-role
                  operator: In
                  values:
                    - executor   # 👈 关键
            matchLabelKeys:
              - spark-app-selector
            topologyKey: topology.kubernetes.io/zone