{{- if and .Values.azure.workloadIdentity.enabled .Values.azure.workloadIdentity.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hive-metastore.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azure.tenantId | quote }}
    {{- with .Values.azure.workloadIdentity.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
