apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-historyserver
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: flink-historyserver
          image: azure/flink:2.2.0
          command: ["/opt/flink/bin/historyserver.sh"]
          env:
            - name: FLINK_HISTORYSERVER_OPTS
              value: |
                -Xms6g
                -Xmx6g
                -Dhistoryserver.web.port=8082
                -Djobmanager.archive.fs.dir=abfss://flink@account.dfs.core.windows.net/archives
                -Dhadoop.fs.azure.account.auth.type=Custom
                -Dhadoop.fs.azure.account.oauth.provider.type=com.github.azure.hadoop.custom.auth.MSIFileCachedAccessTokenProvider
                -Dhadoop.fs.azure.account.hns.enabled=true
                -Dhadoop.fs.azure.account.oauth2.client.id=${MI_CLIENT_ID}
                -Dhadoop.fs.azure.account.oauth2.msi.endpoin=thttp://169.254.169.254/metadata/identity/oauth2/token
                -Dhadoop.fs.azure.account.oauth2.msi.tenant=${TENANT_ID}
                -Dhadoop.fs.azure.enable.blob.endpoint=true
                -Dhadoop.fs.azure.enable.check.access=false
                -Dsecurity.authentication=false
  selector:
    matchLabels:
      app: flink-historyserver

---
apiVersion: v1
kind: Service
metadata:
  name: flink-historyserver
  namespace: flink
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: flink-historyserver
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
