apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-historyserver
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: historyserver
          image: flink:1.17.2
          command: ["/opt/flink/bin/historyserver.sh"]
          env:
            - name: FLINK_HISTORYSERVER_OPTS
              value: |
                -Xms512m
                -Xmx1024m
                -Dhistoryserver.web.port=8082
                -Djobmanager.archive.fs.dir=abfss://flink@account.dfs.core.windows.net/archives
  selector:
    matchLabels:
      app: hive-metastore