apiVersion: v1
kind: Namespace
metadata:
  name: hive

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-site
  namespace: hive
data:
  hive-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property>
            <name>hive.server2.enable.doAs</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.tez.exec.inplace.progress</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.tez.exec.print.summary</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.exec.scratchdir</name>
            <value>/opt/hive/scratch_dir</value>
        </property>
        <property>
            <name>hive.user.install.directory</name>
            <value>/opt/hive/install_dir</value>
        </property>
        <property>
            <name>tez.runtime.optimize.local.fetch</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.exec.submit.local.task.via.child</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.compactor.worker.threads</name>
            <value>1</value>
        </property>
        <property>
            <name>mapreduce.framework.name</name>
            <value>local</value>
        </property>
        <property>
            <name>tez.local.mode</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>/opt/hive/data/warehouse</value>
        </property>
        <property>
            <name>metastore.metastore.event.db.notification.api.auth</name>
            <value>false</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>com.mysql.cj.jdbc.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:mysql://mysql.mysql.svc.cluster.local:3306/hive?useUnicode=true&amp;useSSL=false&amp;serverTimezone=Asia/Shanghai</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>root</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>password</value>
        </property>    
        <property>
            <name>fs.azure.fns.account.service.type</name>
            <value>BLOB</value>
        </property>
        <property>
            <name>fs.azure.account.hns.enabled</name>
            <value>false</value>
        </property>
        <property>
            <name>fs.azure.account.auth.type</name>
            <value>Custom</value>
        </property>
        <property>
            <name>fs.azure.account.oauth2.msi.endpoint</name>
            <value>http://169.254.169.254/metadata/identity/oauth2/token</value>
        </property>
        <property>
            <name>fs.azure.account.oauth2.msi.tenant</name>
            <value>16b3c013-d300-468d-ac64-7eda0820b6d3</value>
        </property>
        <property>
            <name>fs.azure.account.oauth2.client.id</name>
            <value>${MI_CLIENT_ID}</value>
        </property>
        <property>
            <name>fs.azure.account.oauth.provider.type</name>
            <value>com.github.azure.hadoop.custom.auth.MSIFileCachedAccessTokenProvider</value>
        </property>
        <property>
            <name>hive.metastore.uri</name>
            <value>thrift://hive-metastore-service.hive.svc.cluster.local:9083</value>
        </property>
        <property>
            <name>fs.azure.custom.token.file.cache.path</name>
            <value>/tmp/.azure</value>
        </property>
    </configuration>


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      nodeSelector:
        hive: "support"
      containers:
        - name: hive-metastore
          image: ${ACR_LOGIN_SERVER}/azure/hive:3.1.3-4
          env:
            - name: SERVICE_OPTS
              value: "-Xmx12g"
          ports:
            - name: thrift
              containerPort: 9083
          resources:
            requests:
              memory: "16Gi"
              cpu: "4"
          volumeMounts:
            - name: hive-metastore-volume
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
              readOnly: true
      volumes:
        - name: hive-metastore-volume
          configMap:
            name: hive-site
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: hive-metastore
  ports:
    - protocol: TCP
      port: 9083
      targetPort: 9083

